import{a as L,S as w,i as n}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const q="https://pixabay.com/api/";async function h(e,o){return(await L(q,{params:{key:"43997530-fac9ffe50b9517751943b9e7a",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15}})).data}document.querySelector(".gallery");function p(){new w("gallery, a",{captionsData:"alt",captionDelay:250}).refresh()}function F(e){return`<li class="img-item">
    <a class="img-link" href="${e.largeImageURL}">
    <img class="image" src ="${e.webformatURL}" alt ="${e.tags}">
    </a>
    <div class="img-info">
    <p class="info"><b>Likes</b>${e.likes}</p>
    <p class="info"><b>Views</b>${e.views}</p>
    <p class="info"><b>Comments</b>${e.comments}</p>
    <p class="info"><b>Downloads</b>${e.downloads}</p>
    </div>
    </li>`}function g(e){return e.map(F).join("")}const S=document.querySelector(".form"),u=document.querySelector(".gallery"),y=document.querySelector(".loader"),m=document.querySelector(".btn-load-more");S.addEventListener("submit",B);m.addEventListener("click",A);let a=1,c="";f();function b(){y.style.display="block"}function d(){y.style.display="none"}function v(){m.classList.remove("hidden")}function f(){m.classList.add("hidden")}async function B(e){if(e.preventDefault(),u.innerHTML="",f(),b(),c=e.target.elements.query.value.trim(),!c){d(),n.error({message:"Sorry, there are no images matching your search query.",messageColor:"#FAFAFB",color:"#EF4040",position:"topRight"});return}try{const o=await h(c,a);if(o.hits.length===0)n.error({message:"Sorry, there are no images matching your search query.",messageColor:"#FAFAFB",color:"#EF4040",position:"topRight"});else{const s=g(o.hits);u.innerHTML=s,p(),v()}}catch{n.error({message:"Sorry, there are no images matching your search query.",messageColor:"#FAFAFB",color:"#EF4040",position:"topRight"})}finally{e.target.reset(),d()}}async function A(){a+=1,b();const e=await h(c,a);try{const o=g(e.hits);u.insertAdjacentHTML("beforeend",o),p(),a*e.hits.length>=e.totalHits&&(f(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const i=document.querySelector(".img-item").getBoundingClientRect().height;window.scrollBy({left:0,top:i,behavior:"smooth"})}catch{n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}finally{d()}}
//# sourceMappingURL=commonHelpers.js.map
